### ISSUE TITLE
Missing editor config

### ISSUE THREAD

**Issue by halkeye** [christinatruong/llc-html-css-valentines#1]
> This project uses editorconfig to maintain consistent coding style. Make sure your text editor has an editorconfig plugin installed.

The file seems to be missing. I love seeing editor config, I just wanted to find out if it should be there, or the line of text should be removed.

**Comment by christinatruong** [comment]
Oops I forgot to add!  Thanks for this.  Will add it sometime today.

**Comment by christinatruong** [comment]
Added! But you should refer to the LLC repo from now on: https://github.com/ladieslearningcode/llc-html-css-valentines - Just realized I made updates there and not here and now the commit history is all off but the LLC one will always have the latest version anyway :)

**Comment by halkeye** [comment]
Awesome

I only wrote the bug on your repo because I can't create issues on the LLC ones.

**Comment by christinatruong** [comment]
Oops I forgot to turn that on too! All should be good for real now!

**Comment by halkeye** [comment]
Awesome thanks

PS, I'm loving how you are using the gh-pages stuff so people can view the slides online without downloading everything

**Comment by christinatruong** [comment]
Thank you!  :100:
